server:
  port: 8001


spring:
  application:
    name: cloud-payment-provider-hystrix
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.159.212.210:3306/test
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cxw.springcloud.entity

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: payment8001${random.value}
    prefer-ip-address: true #eureka服务页鼠标悬停可以显示ip地址
    lease-renewal-interval-in-seconds: 30 #发送心跳时间
    lease-expiration-duration-in-seconds: 90 #距离上一次心跳的等待上限