server:
  port: 8401
spring:
  application:
    name: sentienl-client-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: http://127.0.0.1:9090
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"