server:
  port: 7001
eureka:
  instance:
    hostname: localhost #eurekaSever的实例名称
  client:
    register-with-eureka: false #不注册自己
    fetch-registry: false
    #客户端与eurekaServer交互的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/