server:
  port: 8000


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: cloud-consumer-order
ribbon:
  ReadTimeout: 5000 #数据传输时间
  ConnectTimeout: 5000 #连接建立时间
logging:
  level:
    com.cxw.service.FeignServiceClient: debug
