server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh1 #路由id，没有固定规则但命名要唯一
          uri: http://localhost:8001 #匹配扣提供服务的路由地址
          predicates:
            - Path=/payments/test1/** #断言，相应匹配的路径进行路由，相当于nginx location
        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payments/test2/**
eureka:
  instance:
    hostname: cloud-gateway
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002/eureka/

