server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001 #eurekaSever的实例名称
  client:
    register-with-eureka: false #不注册自己
    fetch-registry: false
    #客户端与eurekaServer交互的地址
    service-url:
      defaultZone: http://eureka7002:7002/eureka/
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 30000 #定时检测时间，默认60s

spring:
  application:
    name: eureka-server-7001